title: The Oneironaut's Log # your name (or website title) here
logo: "/images/EricProfile-Cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This page serves as a crossroads to various writing samples I've created. Some I do for fun, some are to help others.
  <br><br>
  <a href="https://www.linkedin.com/in/eric-ponvelle-276b0133/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-210993623 # your Google Analytics tracking ID here
